
V_cits<-function(dparms) {
	list2env(as.list(dparms), envir=environment())
	top <- 0
	top <- top + totaltime^4
	top <- top + -totaltime^2
	top <- top + -12*ar^2
	top <- top + -12*ar^3
	top <- top + -totaltime^4*ar^3
	top <- top + -23*totaltime^2*ar^3
	top <- top + -16*totaltime^3*ar^2
	top <- top + -8*totaltime*ar
	top <- top + -3*totaltime^4*ar
	top <- top + 3*totaltime^2*ar
	top <- top + 3*totaltime^4*ar^2
	top <- top + 4*totaltime*ar^2
	top <- top + 8*totaltime^3*ar
	top <- top + 8*totaltime^3*ar^3
	top <- top + 21*totaltime^2*ar^2
	top <- top + 28*totaltime*ar^3

	bot <- 0
	bot <- bot + -24*Pm*ar^3*mtotal
	bot <- bot + -12*Pm*ar^4*mtotal
	bot <- bot + -12*Pm^2*ar^4*mtotal
	bot <- bot + -12*Pm^2*ar^5*mtotal
	bot <- bot + 12*Pm*ar^5*mtotal
	bot <- bot + Pm*Ptime*totaltime^5*mtotal
	bot <- bot + Pm*totaltime^4*ar^5*mtotal
	bot <- bot + Pm^2*Ptime^2*totaltime^3*mtotal
	bot <- bot + -Pm*Ptime*totaltime^3*mtotal
	bot <- bot + -67*Pm*totaltime^2*ar^4*mtotal
	bot <- bot + -40*Pm*totaltime^3*ar^3*mtotal
	bot <- bot + -28*Pm*totaltime*ar^5*mtotal
	bot <- bot + -18*Pm^2*totaltime*ar^3*mtotal
	bot <- bot + -18*Pm^2*totaltime^2*ar^5*mtotal
	bot <- bot + -16*Pm*totaltime*ar^2*mtotal
	bot <- bot + -12*Pm^2*totaltime^3*ar^4*mtotal
	bot <- bot + -8*Pm*totaltime^3*ar^5*mtotal
	bot <- bot + -7*Pm*totaltime^4*ar^2*mtotal
	bot <- bot + -6*Pm^2*totaltime*ar^4*mtotal
	bot <- bot + -6*Pm^2*totaltime^2*ar^2*mtotal
	bot <- bot + -6*Pm^2*totaltime^2*ar^3*mtotal
	bot <- bot + -5*Pm*totaltime^4*ar^4*mtotal
	bot <- bot + -4*Pm^2*Ptime^2*totaltime^5*mtotal
	bot <- bot + -4*Pm^2*totaltime^3*ar^2*mtotal
	bot <- bot + -3*Pm^2*Ptime^4*totaltime^5*mtotal
	bot <- bot + -2*Pm*totaltime^2*ar*mtotal
	bot <- bot + -2*Pm^2*totaltime*ar^2*mtotal
	bot <- bot + 2*Pm*totaltime^4*ar*mtotal
	bot <- bot + 4*Pm^2*totaltime^3*ar^5*mtotal
	bot <- bot + 6*Pm^2*Ptime^3*totaltime^5*mtotal
	bot <- bot + 7*Pm*totaltime^2*ar^2*mtotal
	bot <- bot + 9*Pm*totaltime^4*ar^3*mtotal
	bot <- bot + 12*Pm^2*totaltime^3*ar^3*mtotal
	bot <- bot + 16*Pm*totaltime*ar^3*mtotal
	bot <- bot + 16*Pm*totaltime^3*ar^2*mtotal
	bot <- bot + 23*Pm*totaltime^2*ar^5*mtotal
	bot <- bot + 26*Pm^2*totaltime*ar^5*mtotal
	bot <- bot + 30*Pm^2*totaltime^2*ar^4*mtotal
	bot <- bot + 32*Pm*totaltime^3*ar^4*mtotal
	bot <- bot + 39*Pm*totaltime^2*ar^3*mtotal
	bot <- bot + 52*Pm*totaltime*ar^4*mtotal
	bot <- bot + Pm^2*Ptime^2*totaltime^3*ar*mtotal
	bot <- bot + -Pm*Ptime*totaltime^5*ar^5*mtotal
	bot <- bot + -84*Pm^2*Ptime*totaltime^3*ar^4*mtotal
	bot <- bot + -62*Pm*Ptime*totaltime^3*ar^3*mtotal
	bot <- bot + -60*Pm^2*Ptime^3*totaltime^5*ar^3*mtotal
	bot <- bot + -52*Pm*Ptime*totaltime^2*ar^4*mtotal
	bot <- bot + -48*Pm^2*Ptime*totaltime^4*ar^3*mtotal
	bot <- bot + -48*Pm^2*Ptime^3*totaltime^4*ar^2*mtotal
	bot <- bot + -48*Pm^2*Ptime^3*totaltime^4*ar^4*mtotal
	bot <- bot + -40*Pm^2*Ptime^2*totaltime^5*ar^2*mtotal
	bot <- bot + -36*Pm^2*Ptime^2*totaltime^4*ar^3*mtotal
	bot <- bot + -36*Pm^2*Ptime^4*totaltime^4*ar^3*mtotal
	bot <- bot + -34*Pm^2*Ptime*totaltime^2*ar^5*mtotal
	bot <- bot + -32*Pm*Ptime*totaltime^4*ar^2*mtotal
	bot <- bot + -32*Pm*Ptime*totaltime^4*ar^4*mtotal
	bot <- bot + -30*Pm^2*Ptime^3*totaltime^5*ar*mtotal
	bot <- bot + -30*Pm^2*Ptime^4*totaltime^5*ar^2*mtotal
	bot <- bot + -23*Pm*Ptime*totaltime^3*ar^5*mtotal
	bot <- bot + -20*Pm^2*Ptime*totaltime^2*ar^2*mtotal
	bot <- bot + -20*Pm^2*Ptime^2*totaltime^5*ar^4*mtotal
	bot <- bot + -15*Pm^2*Ptime^4*totaltime^5*ar^4*mtotal
	bot <- bot + -12*Pm*Ptime*totaltime*ar^2*mtotal
	bot <- bot + -12*Pm*Ptime*totaltime*ar^5*mtotal
	bot <- bot + -12*Pm^2*Ptime*totaltime*ar^3*mtotal
	bot <- bot + -12*Pm^2*Ptime*totaltime*ar^4*mtotal
	bot <- bot + -12*Pm^2*Ptime*totaltime^3*ar^2*mtotal
	bot <- bot + -12*Pm^2*Ptime^2*totaltime^2*ar^3*mtotal
	bot <- bot + -10*Pm*Ptime*totaltime^5*ar^3*mtotal
	bot <- bot + -10*Pm^2*Ptime^2*totaltime^3*ar^3*mtotal
	bot <- bot + -8*Pm*Ptime*totaltime^2*ar*mtotal
	bot <- bot + -8*Pm^2*Ptime*totaltime^4*ar*mtotal
	bot <- bot + -8*Pm^2*Ptime*totaltime^4*ar^5*mtotal
	bot <- bot + -7*Pm^2*Ptime^2*totaltime^3*ar^5*mtotal
	bot <- bot + -6*Pm^2*Ptime*totaltime^3*ar*mtotal
	bot <- bot + -6*Pm^2*Ptime^2*totaltime^4*ar*mtotal
	bot <- bot + -6*Pm^2*Ptime^4*totaltime^4*ar*mtotal
	bot <- bot + -6*Pm^2*Ptime^2*totaltime^4*ar^5*mtotal
	bot <- bot + -6*Pm^2*Ptime^3*totaltime^5*ar^5*mtotal
	bot <- bot + -6*Pm^2*Ptime^4*totaltime^4*ar^5*mtotal
	bot <- bot + -5*Pm*Ptime*totaltime^5*ar*mtotal
	bot <- bot + -2*Pm^2*Ptime^2*totaltime^3*ar^2*mtotal
	bot <- bot + 2*Pm^2*Ptime*totaltime^2*ar*mtotal
	bot <- bot + 3*Pm^2*Ptime^4*totaltime^5*ar^5*mtotal
	bot <- bot + 4*Pm^2*Ptime^2*totaltime^5*ar^5*mtotal
	bot <- bot + 5*Pm*Ptime*totaltime^3*ar*mtotal
	bot <- bot + 5*Pm*Ptime*totaltime^5*ar^4*mtotal
	bot <- bot + 6*Pm^2*Ptime^2*totaltime^2*ar*mtotal
	bot <- bot + 6*Pm^2*Ptime^2*totaltime^2*ar^5*mtotal
	bot <- bot + 8*Pm*Ptime*totaltime^4*ar*mtotal
	bot <- bot + 8*Pm*Ptime*totaltime^4*ar^5*mtotal
	bot <- bot + 10*Pm*Ptime*totaltime^5*ar^2*mtotal
	bot <- bot + 12*Pm*Ptime*totaltime*ar^3*mtotal
	bot <- bot + 12*Pm*Ptime*totaltime*ar^4*mtotal
	bot <- bot + 12*Pm*Ptime*totaltime^2*ar^3*mtotal
	bot <- bot + 12*Pm^2*Ptime*totaltime*ar^2*mtotal
	bot <- bot + 12*Pm^2*Ptime*totaltime*ar^5*mtotal
	bot <- bot + 12*Pm^2*Ptime^3*totaltime^4*ar*mtotal
	bot <- bot + 12*Pm^2*Ptime^3*totaltime^4*ar^5*mtotal
	bot <- bot + 14*Pm*Ptime*totaltime^3*ar^2*mtotal
	bot <- bot + 15*Pm^2*Ptime^4*totaltime^5*ar*mtotal
	bot <- bot + 17*Pm^2*Ptime^2*totaltime^3*ar^4*mtotal
	bot <- bot + 20*Pm*Ptime*totaltime^2*ar^2*mtotal
	bot <- bot + 20*Pm^2*Ptime^2*totaltime^5*ar*mtotal
	bot <- bot + 24*Pm^2*Ptime^2*totaltime^4*ar^2*mtotal
	bot <- bot + 24*Pm^2*Ptime^2*totaltime^4*ar^4*mtotal
	bot <- bot + 24*Pm^2*Ptime^4*totaltime^4*ar^2*mtotal
	bot <- bot + 24*Pm^2*Ptime^4*totaltime^4*ar^4*mtotal
	bot <- bot + 28*Pm*Ptime*totaltime^2*ar^5*mtotal
	bot <- bot + 30*Pm^2*Ptime*totaltime^3*ar^5*mtotal
	bot <- bot + 30*Pm^2*Ptime^3*totaltime^5*ar^4*mtotal
	bot <- bot + 30*Pm^2*Ptime^4*totaltime^5*ar^3*mtotal
	bot <- bot + 32*Pm^2*Ptime*totaltime^4*ar^2*mtotal
	bot <- bot + 32*Pm^2*Ptime*totaltime^4*ar^4*mtotal
	bot <- bot + 40*Pm^2*Ptime^2*totaltime^5*ar^3*mtotal
	bot <- bot + 48*Pm*Ptime*totaltime^4*ar^3*mtotal
	bot <- bot + 52*Pm^2*Ptime*totaltime^2*ar^4*mtotal
	bot <- bot + 60*Pm^2*Ptime^3*totaltime^5*ar^2*mtotal
	bot <- bot + 67*Pm*Ptime*totaltime^3*ar^4*mtotal
	bot <- bot + 72*Pm^2*Ptime*totaltime^3*ar^3*mtotal
	bot <- bot + 72*Pm^2*Ptime^3*totaltime^4*ar^3*mtotal

	return(top/bot)
}
