
V_its<-function(dparms) {
	list2env(as.list(dparms), envir=environment())
	top <- 0
	top <- top + totaltime^4
	top <- top + -totaltime^2
	top <- top + -12*ar^2
	top <- top + -12*ar^3
	top <- top + -totaltime^4*ar^3
	top <- top + -23*totaltime^2*ar^3
	top <- top + -16*totaltime^3*ar^2
	top <- top + -8*totaltime*ar
	top <- top + -3*totaltime^4*ar
	top <- top + 3*totaltime^2*ar
	top <- top + 3*totaltime^4*ar^2
	top <- top + 4*totaltime*ar^2
	top <- top + 8*totaltime^3*ar
	top <- top + 8*totaltime^3*ar^3
	top <- top + 21*totaltime^2*ar^2
	top <- top + 28*totaltime*ar^3

	bot <- 0
	bot <- bot + -24*ar^3*mtotal
	bot <- bot + -24*ar^4*mtotal
	bot <- bot + Ptime*totaltime^5*mtotal
	bot <- bot + Ptime^2*totaltime^3*mtotal
	bot <- bot + totaltime^2*ar^2*mtotal
	bot <- bot + totaltime^4*ar^5*mtotal
	bot <- bot + -Ptime*totaltime^3*mtotal
	bot <- bot + -37*totaltime^2*ar^4*mtotal
	bot <- bot + -28*totaltime^3*ar^3*mtotal
	bot <- bot + -18*totaltime*ar^2*mtotal
	bot <- bot + -7*totaltime^4*ar^2*mtotal
	bot <- bot + -5*totaltime^4*ar^4*mtotal
	bot <- bot + -4*Ptime^2*totaltime^5*mtotal
	bot <- bot + -4*totaltime^3*ar^5*mtotal
	bot <- bot + -3*Ptime^4*totaltime^5*mtotal
	bot <- bot + -2*totaltime*ar^3*mtotal
	bot <- bot + -2*totaltime*ar^5*mtotal
	bot <- bot + -2*totaltime^2*ar*mtotal
	bot <- bot + 2*totaltime^4*ar*mtotal
	bot <- bot + 5*totaltime^2*ar^5*mtotal
	bot <- bot + 6*Ptime^3*totaltime^5*mtotal
	bot <- bot + 9*totaltime^4*ar^3*mtotal
	bot <- bot + 12*totaltime^3*ar^2*mtotal
	bot <- bot + 20*totaltime^3*ar^4*mtotal
	bot <- bot + 33*totaltime^2*ar^3*mtotal
	bot <- bot + 46*totaltime*ar^4*mtotal
	bot <- bot + Ptime^2*totaltime^3*ar*mtotal
	bot <- bot + -Ptime*totaltime^3*ar*mtotal
	bot <- bot + -Ptime*totaltime^5*ar^5*mtotal
	bot <- bot + -60*Ptime^3*totaltime^5*ar^3*mtotal
	bot <- bot + -48*Ptime^3*totaltime^4*ar^2*mtotal
	bot <- bot + -48*Ptime^3*totaltime^4*ar^4*mtotal
	bot <- bot + -40*Ptime^2*totaltime^5*ar^2*mtotal
	bot <- bot + -36*Ptime^2*totaltime^4*ar^3*mtotal
	bot <- bot + -36*Ptime^4*totaltime^4*ar^3*mtotal
	bot <- bot + -30*Ptime^3*totaltime^5*ar*mtotal
	bot <- bot + -30*Ptime^4*totaltime^5*ar^2*mtotal
	bot <- bot + -20*Ptime^2*totaltime^5*ar^4*mtotal
	bot <- bot + -17*Ptime*totaltime^3*ar^4*mtotal
	bot <- bot + -15*Ptime^4*totaltime^5*ar^4*mtotal
	bot <- bot + -12*Ptime^2*totaltime^2*ar^3*mtotal
	bot <- bot + -10*Ptime*totaltime^5*ar^3*mtotal
	bot <- bot + -10*Ptime^2*totaltime^3*ar^3*mtotal
	bot <- bot + -7*Ptime^2*totaltime^3*ar^5*mtotal
	bot <- bot + -6*Ptime*totaltime^2*ar*mtotal
	bot <- bot + -6*Ptime*totaltime^2*ar^5*mtotal
	bot <- bot + -6*Ptime^2*totaltime^4*ar*mtotal
	bot <- bot + -6*Ptime^4*totaltime^4*ar*mtotal
	bot <- bot + -6*Ptime^2*totaltime^4*ar^5*mtotal
	bot <- bot + -6*Ptime^3*totaltime^5*ar^5*mtotal
	bot <- bot + -6*Ptime^4*totaltime^4*ar^5*mtotal
	bot <- bot + -5*Ptime*totaltime^5*ar*mtotal
	bot <- bot + -2*Ptime^2*totaltime^3*ar^2*mtotal
	bot <- bot + 2*Ptime*totaltime^3*ar^2*mtotal
	bot <- bot + 3*Ptime^4*totaltime^5*ar^5*mtotal
	bot <- bot + 4*Ptime^2*totaltime^5*ar^5*mtotal
	bot <- bot + 5*Ptime*totaltime^5*ar^4*mtotal
	bot <- bot + 6*Ptime^2*totaltime^2*ar*mtotal
	bot <- bot + 6*Ptime^2*totaltime^2*ar^5*mtotal
	bot <- bot + 7*Ptime*totaltime^3*ar^5*mtotal
	bot <- bot + 10*Ptime*totaltime^3*ar^3*mtotal
	bot <- bot + 10*Ptime*totaltime^5*ar^2*mtotal
	bot <- bot + 12*Ptime*totaltime^2*ar^3*mtotal
	bot <- bot + 12*Ptime^3*totaltime^4*ar*mtotal
	bot <- bot + 12*Ptime^3*totaltime^4*ar^5*mtotal
	bot <- bot + 15*Ptime^4*totaltime^5*ar*mtotal
	bot <- bot + 17*Ptime^2*totaltime^3*ar^4*mtotal
	bot <- bot + 20*Ptime^2*totaltime^5*ar*mtotal
	bot <- bot + 24*Ptime^2*totaltime^4*ar^2*mtotal
	bot <- bot + 24*Ptime^2*totaltime^4*ar^4*mtotal
	bot <- bot + 24*Ptime^4*totaltime^4*ar^2*mtotal
	bot <- bot + 24*Ptime^4*totaltime^4*ar^4*mtotal
	bot <- bot + 30*Ptime^3*totaltime^5*ar^4*mtotal
	bot <- bot + 30*Ptime^4*totaltime^5*ar^3*mtotal
	bot <- bot + 40*Ptime^2*totaltime^5*ar^3*mtotal
	bot <- bot + 60*Ptime^3*totaltime^5*ar^2*mtotal
	bot <- bot + 72*Ptime^3*totaltime^4*ar^3*mtotal

	return(top/bot)
}
