---
title: "Lab for randomization"
output: word_document
---

```{r, setup, include=FALSE}
load("../Planner/appData.Rdata")
```

# Randomization in General

## Important Note

Randomization can be a very complex task. The purpose of this lab is to give everyone a feel for what is ultimately done with computer algorithms. The hope is that you can explore these topics during this lab.

# Case Study

## **Museum Science Spatial Program for Pre-Schoolers**

A STEM Museum in Florida has had a longstanding partnership with two researchers at a nearby university. Drs. Andrews and Zheng are interested in how informal experiences in museums may encourage families to engage with their children in ways that inspire and support STEM learning at home. This interest has led them to work with the museum staff to design a series of exhibits that foster interactions (while at the museum), while also providing materials to take home, with the hope of continued engagement. Understanding if this program actually improves these connections is important, given the continued cost of these take-home materials. This study focuses on a particular exhibit that focuses on fostering the development of spatial skills through a series of building activities.

# Plausible Evaluation Design

## Individual Random Assignment

Suppose researchers wish to evaluate the effectiveness of a similar program on parent interaction with their children at home, measured using a well-established validated scale based on questions answered through an online survey collection system. The design is to recruit families as they enter the museum into the study, then randomly assign them to attend the additional exhibits and receive the additional take home materials (treatment group) or attend the typical exhibits (control group). After 30 days, all study families take a survey and their answers are used to compute an outcome score.

### Question 1

Using the [planner tool](https://steppcenter.shinyapps.io/Planner/), randomize 16 families where 8 families are selected to the intervention. Do this five times (you can press the randomization/re-randomization button), recording which of the 16 families are randomized to the intervention group in the table below (e.g., you can mark the cell with an "X" or a check)

| Family | A   | B   | C   | D   | E   |
|--------|-----|-----|-----|-----|-----|
| 1      |     |     |     |     |     |
| 2      |     |     |     |     |     |
| 3      |     |     |     |     |     |
| 4      |     |     |     |     |     |
| 5      |     |     |     |     |     |
| 6      |     |     |     |     |     |
| 7      |     |     |     |     |     |
| 8      |     |     |     |     |     |
| 9      |     |     |     |     |     |
| 10     |     |     |     |     |     |
| 11     |     |     |     |     |     |
| 12     |     |     |     |     |     |
| 13     |     |     |     |     |     |
| 14     |     |     |     |     |     |
| 15     |     |     |     |     |     |
| 16     |     |     |     |     |     |

Suppose you were able to jump around the multiverse like Dr. Strange and his friends, how many families are in the intervention all five times?

### Question 2

How many ways can 16 families be randomized where 8 receive the intervention?

### Question 3

A member of the study team claims that a better study would use a higher portion of the study families as treatment. Using the [planner tool](https://steppcenter.shinyapps.io/Planner/), randomize 16 families where 12 families are selected to the intervention. Do this five times (you can press the randomization/re-randomization button), recording which of the 16 families are randomized to the intervention group in the table below (e.g., you can mark the cell with an "X" or a check)

| Family | A   | B   | C   | D   | E   |
|--------|-----|-----|-----|-----|-----|
| 1      |     |     |     |     |     |
| 2      |     |     |     |     |     |
| 3      |     |     |     |     |     |
| 4      |     |     |     |     |     |
| 5      |     |     |     |     |     |
| 6      |     |     |     |     |     |
| 7      |     |     |     |     |     |
| 8      |     |     |     |     |     |
| 9      |     |     |     |     |     |
| 10     |     |     |     |     |     |
| 11     |     |     |     |     |     |
| 12     |     |     |     |     |     |
| 13     |     |     |     |     |     |
| 14     |     |     |     |     |     |
| 15     |     |     |     |     |     |
| 16     |     |     |     |     |     |

Suppose again you were able to jump around the multiverse like Dr. Strange and his friends, how many families are in the intervention all five times?

### Question 4

How many ways can 16 families be randomized where 12 receive the intervention?

### Question 5

A member of the study team claims that a better study would use a lower portion of the study families as treatment. Using the [planner tool](https://steppcenter.shinyapps.io/Planner/), randomize 16 families where 4 families are selected to the intervention. How many ways can 16 families be randomized where 4 receive the intervention?

### Question 6

Using the [planner tool](https://steppcenter.shinyapps.io/Planner/), randomize 16 families where 4 families are selected to the intervention, again. This time, however, choose to set a seed and leave the default 123456. You can press the randomization/re-randomization button, too. Compare the status of family 12 with another student. Is it the same? With the same friend, pick another number and enter it into the seed field. Did the status change? Did you both get the same result for family 12? How about other families?


