---
title: "Lab for non-equivalent control group cluster matching"
subtitle: "Chapter 12"
output: word_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r, setup, include=FALSE}
load("../Planner/appData.Rdata")
```

## Important Note

Matching is a very complex task. The purpose of this lab is to give
everyone a feel for what is ultimately done with computer algorithms.
The hope is that you can explore these topics during this lab. We
encourage you to not feel frustrated if a perfect solution is
unattainable: it rarely is!

# Case Study

## **Elementary School Project-Based Learning Program**

Over the past five years, Dr. Wanda Smith and colleagues have been
working closely with Detroit public schools to develop an innovative,
hands-on science program for elementary school teachers and their
students. During this time, Dr. Smith has worked closely with teachers
in three elementary schools to develop and refine a professional
development program and science units focused on environmental science
and biology with children in grades 3-5. These units are hands-on and
project-based and focus not only on scientific knowledge but also on
centering students as scientists and observers in their communities.
Over time, the team has developed five science units, associated
activities, and teaching guidelines. Teachers are deeply engaged in this
work and observations in the classrooms suggest that students are,
indeed, making connections between science and their lives. Student
knowledge of science seems to have increased, as does student
motivation.

+---------------+------------------------------------------------------+
| PICO          | Details                                              |
+===============+======================================================+
| Population    | Elementary school teachers and students in grades    |
|               | 3-5 in elementary schools in Detroit serving high    |
|               | percents of low-SES, majority Black students         |
+---------------+------------------------------------------------------+
| Intervention  | Professional Development program (teachers) +        |
|               | Science units                                        |
+---------------+------------------------------------------------------+
| Comparison    | In these schools, science is otherwise taught using  |
|               | textbooks                                            |
+---------------+------------------------------------------------------+
| Outcome       | Motivation, Science test                             |
+---------------+------------------------------------------------------+

# Plausible Evaluation Design

## Matching Entire Clusters (Schools)

Suppose researchers wish to evaluate the effectiveness of a similar
program on student science motivation. Researchers enrolled schools in
the program during the summer to serve as treatment schools and now need
to examine the rest of schools in the state to find equivalent matches.
School average of a state test scaled to have a mean of 50 and standard
deviation of 10.

## Scenario A: Seemingly Unrelated Treatment Assignment

In the [planner tool](https://steppcenter.shinyapps.io/Planner/), select
the `QED Selection` tab and pick the "random selection" scenario. In
this scenario, the state has
`r length(table(qed_data$between_random$school))` schools and
`r length(qed_data$between_random_treatlist)` of them are in your
program. A random selection of
`r length(qed_data$between_random_comparelist)` comparison schools has
been made for you.

Examine the "Balance Statistics between Treatment and Control" table.
The columns for `nonwhite` and `ses` columns represent the balance in
standard deviation units for student level indicators of being a student
of color and having a lower socioeconomic status. The `pretest` is also
a balance statistic, but for a test score covariate. The `urban` column
is another balance statistic, but this is a school-level variable.

The table under "Means across Students by Treatment and Control" give
averages (proportions for `nonwhite`, `ses`, and `urban`, and the mean
`pretest` score for a scale that ranges from 0 to 100 with a mean of
50).

Under "Select Schools" you find two fields that allow you to add or
remove schools from the comparison and treatment group. The "Explore"
tabs allow you to examine the means of each school and sort on columns
(such as the Mahalanobis Distance of the possible comparison schools.

### Question A-1

Note the column `Mahalanobis Distance` in the "Balance Statistics"
table, it currently reads `2.02`. Next, under "Comparison Schools", sort
the comparison pool by the `Mahalanobis Distance` column. You will see
that school `281` has a large distance metric. Under "Select Schools,"
add school 281 to the comparison pool. Check the "Balance Statistics"
table, what happened?

### Question A-2

Remove school `281` from your comparison selection. Your selections
should now read `r qed_data$between_random_comparelist`. Schools `354`
`307`, and `239` seem to have high distances. Remove one or two of them
from the comparison list, what do you notice about the balance
statistics?

### Question A-3

Next, remove all schools from the comparison list. Using the "Comparison
Schools" table, sort on `Mahalanobis Distance`. Adjust the table to show
10 entries. What do you notice in the urban column? Select these schools
10 schools. Examine the "Balance Statistics" and "Means across Students
by Treatment and Control" table.

What would you do?

### Question A-4

After thinking about what you would do, use the tool to come up with a
good set of 10 comparison schools. If stuck, see if you can find a
treatment school or two to remove.

## Scenario B: Treatment Assignment Related to Average Pretest

In the [planner tool](https://steppcenter.shinyapps.io/Planner/), select
the `QED Selection` tab and pick the "Systematic Selection" scenario. In
this scenario, the state has
`r length(table(qed_data$between_biased$school))` schools and
`r length(qed_data$between_biased_treatlist)` of them are in your
program. A random selection of
`r length(qed_data$between_biased_comparelist)` comparison schools has
been made for you.

The tools are the same, except these data have be rigged so that the
likelihood of schools being part of the program is positively related to
the average student scores.

### Question B

Using the metrics available to you, and knowing the selection
relationship with test score averages, attempt to build a sample.

### Bonus

Revisit your solutions, but occasionally return to the "Power and MDES"
tab to see if your designs have adequate sensitivity.
